# Create PostgreSQL Names
make_db_table_name <- function(table_name) {
  . <- table_name
  . <- gsub("\\.+", "_", tolower(make.names(table_name)))
  . <- gsub("-", "_", .)
  . <- gsub("19([0-9][0-9])", "\\1", .)
  . <- gsub("20([0-9][0-9])", "\\1", .)
  . <- gsub("([0-9][0-9])_([0-9][0-9])", "\\1\\2", .)
  . <- gsub("students?", "stu", .)
  . <- gsub("county", "ct", .)
  . <- gsub("block_?group", "bg", .)
  . <- gsub("census_?tract", "tr", .)
  . <- gsub("one", "1", .)
  . <- gsub("first", "1st", .)
  . <- gsub("two", "2", .)
  . <- gsub("second", "2nd", .)
  . <- gsub("three", "3", .)
  . <- gsub("third", "3rd", .)
  . <- gsub("four", "4", .)
  . <- gsub("five", "5", .)
  . <- gsub("six", "6", .)
  . <- gsub("seven", "7", .)
  . <- gsub("year", "yr", .)
  . <- gsub("served", "srvd", .)
  . <- gsub("virginia", "va", .)
  . <- gsub("kindergarten|kindergartener", "kg", .)
  . <- gsub("less than", "less", .)
  . <- gsub("below", "less", .)
  . <- gsub("readiness", "ready", .)
  . <- gsub("levels", "lvls", .)
  . <- gsub("score", "scr", .)
  . <- gsub("who|are|whose|were|for|subject|or", "", .)
  . <- gsub("preschool", "pk", .)
  . <- gsub("initiative", "init", .)
  . <- gsub("passage", "pass", .)
  . <- gsub("rate", "rt", .)
  . <- gsub("grade", "gr", .)
  . <- gsub("place", "pl", .)
  . <- gsub("reading", "read", .)
  . <- gsub("standards_of_learning.+(sol)", "\\1", .)
  . <- gsub("standards_of_learning", "sol", .)
  . <- gsub("economic|economically", "econ", .)
  . <- gsub("advantage", "advtg", .)
  . <- gsub("high_?school", "hs", .)
  . <- gsub("graduate|graduation", "grad", .)
  . <- gsub("household", "hshld", .)
  . <- gsub("income", "inc", .)
  . <- gsub("median", "med", .)
  . <- gsub("approve", "aprv", .)
  . <- gsub("price", "prc", .)
  . <- gsub("lunch", "lnch", .)
  . <- gsub("reduce", "rdc", .)
  . <- gsub("school", "sch", .)
  . <- gsub("children", "child", .)
  . <- gsub("family|familie", "fam", .)
  . <- gsub("with", "w", .)
  . <- gsub("service", "srv", .)
  . <- gsub("population", "pop", .)
  . <- gsub("_+", "_", .)
  . <- gsub("_$", "", .)
  .
}

